// -*- mode: kotlin -*-

/*
 * AUTOGENERATED BY glean_parser. DO NOT EDIT. DO NOT COMMIT.
 */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. *//* ktlint-disable no-blank-line-before-rbrace */
@file:Suppress("PackageNaming", "MaxLineLength")
package GleanMetrics

import mozilla.components.service.glean.private.EventExtras // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.HistogramType // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.Lifetime // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.MemoryUnit // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.NoExtraKeys // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.NoExtras // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.NoReasonCodes // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.TimeUnit // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.UuidMetricType // ktlint-disable import-ordering

internal object Telemetry {
    /**
     * Lorem ipsum dolor sit amet, consectetur adipiscing elit.
     */
    @get:JvmName("someMetric")
    val someMetric: UuidMetricType by lazy { // generated from telemetry.some_metric
        UuidMetricType(
            category = "telemetry",
            name = "some_metric",
            sendInPings = listOf("custom-ping-might-be-empty"),
            lifetime = Lifetime.Ping,
            disabled = false
        )
    }
}
