package glean

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// AUTOGENERATED BY {current_version}. DO NOT EDIT.

// required imports
import (
    "encoding/json"
    "errors"
    "fmt"
    "io"
    "strconv"
    "time"

    "github.com/google/uuid"
)

// log type string used to identify logs to process in the Moz Data Pipeline
var gleanEventMozlogType string = "glean-server-event"

// A GleanEventsLogger produces output in the required format for Glean to ingest.
// Glean ingestion requires the output to be written to os.Stdout. Writing to a different
// output will require the consumer to handle any closing as appropriate for the Writer.
// e.g. if writing to a file.
type GleanEventsLogger struct {
    AppID             string // Application Id to identify application per Glean standards
    AppDisplayVersion string // Version of application emitting the event
    AppChannel        string // Channel to differentiate logs from prod/beta/staging/devel
    Writer            io.Writer // Writer to output to. Normal operation expects os.Stdout
}

// exported type for public method parameters
type RequestInfo struct {
    UserAgent string
    IpAddress string
}

// default empty values will be omitted in json from ping struct definition
var defaultRequestInfo = RequestInfo{
    UserAgent: "",
    IpAddress: "",
}

// structs to construct the glean ping
type clientInfo struct {
    TelemetrySDKBuild string `json:"telemetry_sdk_build"`
    FirstRunDate      string `json:"first_run_date"`
    OS                string `json:"os"`
    OSVersion         string `json:"os_version"`
    Architecture      string `json:"architecture"`
    AppBuild          string `json:"app_build"`
    AppDisplayVersion string `json:"app_display_version"`
    AppChannel        string `json:"app_channel"`
}

type pingInfo struct {
    Seq       int    `json:"seq"`
    StartTime string `json:"start_time"`
    EndTime   string `json:"end_time"`
}

type ping struct {
    DocumentNamespace string `json:"document_namespace"`
    DocumentType      string `json:"document_type"`
    DocumentVersion   string `json:"document_version"`
    DocumentID        string `json:"document_id"`
    UserAgent         string `json:"user_agent,omitempty"`
    IpAddress         string `json:"ip_address,omitempty"`
    Payload           string `json:"payload"`
}

type metrics map[string]map[string]any

type pingPayload struct {
    ClientInfo clientInfo   `json:"client_info"`
    PingInfo   pingInfo     `json:"ping_info"`
    Metrics    metrics      `json:"metrics"`
    Events     []gleanEvent `json:"events"`
}

type gleanEvent struct {
    Category  string            `json:"category"`
    Name      string            `json:"name"`
    Timestamp int64             `json:"timestamp"`
    Extra     map[string]string `json:"extra"`
}

type logEnvelope struct {
    Timestamp string
    Logger    string
    Type      string
    Fields    ping
}

// Fields with default values are required in the Glean schema, but not used in server context
func createClientInfo(appDisplayVersion, appChannel string) clientInfo {
    return clientInfo{
        TelemetrySDKBuild: "{current_version}",
        FirstRunDate:      "Unknown",
        OS:                "Unknown",
        OSVersion:         "Unknown",
        Architecture:      "Unknown",
        AppBuild:          "Unknown",
        AppDisplayVersion: appDisplayVersion,
        AppChannel:        appChannel,
    }
}

func createPingInfo() pingInfo {
    now := time.Now().UTC().Format("2006-01-02T15:04:05.000Z")
    return pingInfo{
        Seq:       0,
        StartTime: now,
        EndTime:   now,
    }
}

// resolveDocumentID returns supplied if non-empty, otherwise a fresh UUID.
// Set DocumentID on the ping params struct to share an ID across transports
// (e.g., dual-write verification during a logging->pubsub migration).
func resolveDocumentID(supplied string) (string, error) {
    if supplied != "" {
        return supplied, nil
    }
    id, err := uuid.NewRandom()
    if err != nil {
        return "", err
    }
    return id.String(), nil
}

func (g GleanEventsLogger) createPing(documentType, documentID string, config RequestInfo, payload pingPayload) (ping, error) {
    payloadJson, err := json.Marshal(payload)
    if err != nil {
        return ping{}, err
    }

    return ping{
        DocumentNamespace: g.AppID,
        DocumentType:      documentType,
        DocumentVersion:   "1",
        DocumentID:        documentID,
        UserAgent:         config.UserAgent,
        IpAddress:         config.IpAddress,
        Payload:           string(payloadJson),
    }, nil
}

// method called by each ping-specific record method.
// wrap the payload in the envelope and print to stdout
func (g GleanEventsLogger) record(
    documentType string,
    documentID string,
    requestInfo RequestInfo,
    payload pingPayload,
) error {
    if g.Writer == nil {
        return errors.New("writer not specified")
    }

    ping, err := g.createPing(documentType, documentID, requestInfo, payload)
    if err != nil {
        return err
    }

    envelope := logEnvelope{
        Timestamp: strconv.FormatInt(time.Now().UnixNano(), 10),
        Logger:    "glean",
        Type:      gleanEventMozlogType,
        Fields:    ping,
    }
    envelopeJson, err := json.Marshal(envelope)
    if err != nil {
        return err
    }

    fmt.Fprintln(g.Writer, string(envelopeJson))
    return nil
}

func newGleanEvent(category, name string, extra map[string]string) gleanEvent {
    return gleanEvent{
        Category:  category,
        Name:      name,
        Timestamp: 0,
        Extra: extra,
    }
}

type BackendSpecialEventEvent struct {
    EventFieldString string // A string extra field
    EventFieldQuantity int64 // A quantity extra field
    EventFieldBool bool // A boolean extra field
}

func (e BackendSpecialEventEvent) gleanEvent() gleanEvent {
    return newGleanEvent(
        "backend",
        "special_event",
        map[string]string{
            "event_field_string": e.EventFieldString,
            "event_field_quantity": fmt.Sprintf("%d", e.EventFieldQuantity),
            "event_field_bool": fmt.Sprintf("%t", e.EventFieldBool),
        },
    )
}

type ServerTelemetryScenarioOnePingEvent interface {
    isServerTelemetryScenarioOnePingEvent()
    gleanEvent() gleanEvent
}

func (e BackendSpecialEventEvent) isServerTelemetryScenarioOnePingEvent() {}

type ServerTelemetryScenarioOnePing struct {
    MetricName string // Test string metric
    MetricRequestBool bool // boolean
    MetricRequestCount int64 // Test quantity metric
    MetricRequestDatetime time.Time // Test datetime metric
    MetricRequestStringList []string // Test string_list metric
    Event ServerTelemetryScenarioOnePingEvent // valid event for this ping
    DocumentID string // optional; used as document_id if non-empty, otherwise a fresh UUID is generated
}

// buildPayload assembles the inner pingPayload for `server-telemetry-scenario-one`. Shared by
// the logging and pub/sub code paths.
func (p ServerTelemetryScenarioOnePing) buildPayload(appDisplayVersion, appChannel string) pingPayload {
    // Ensure nil string_list metrics serialize as empty arrays, not null
    if p.MetricRequestStringList == nil {
        p.MetricRequestStringList = []string{}
    }
    metrics := metrics{
        "string": {
            "metric.name": p.MetricName,
        },
        "boolean": {
            "metric.request_bool": p.MetricRequestBool,
        },
        "quantity": {
            "metric.request_count": p.MetricRequestCount,
        },
        "datetime": {
            "metric.request_datetime": p.MetricRequestDatetime.Format("2006-01-02T15:04:05.000Z"),
        },
        "string_list": {
            "metric.request_string_list": p.MetricRequestStringList,
        },
    }

    events := []gleanEvent{}
    if p.Event != nil {
        events = append(events, p.Event.gleanEvent())
    }

    return pingPayload{
        ClientInfo: createClientInfo(appDisplayVersion, appChannel),
        PingInfo:   createPingInfo(),
        Metrics:    metrics,
        Events:     events,
    }
}

// Record and submit `server-telemetry-scenario-one` ping
func (g GleanEventsLogger) RecordServerTelemetryScenarioOnePing(
    requestInfo RequestInfo,
    params ServerTelemetryScenarioOnePing,
) error {
    documentID, err := resolveDocumentID(params.DocumentID)
    if err != nil {
        return fmt.Errorf("resolve document_id: %w", err)
    }
    payload := params.buildPayload(g.AppDisplayVersion, g.AppChannel)
    return g.record("server-telemetry-scenario-one", documentID, requestInfo, payload)
}

// Record and submit `server-telemetry-scenario-one` ping omitting user request info
func (g GleanEventsLogger) RecordServerTelemetryScenarioOnePingWithoutUserInfo(
    params ServerTelemetryScenarioOnePing,
) error {
    return g.RecordServerTelemetryScenarioOnePing(defaultRequestInfo, params)
}
