/*
 * AUTOGENERATED BY glean_parser.  DO NOT EDIT.
 */

object {{ group_name|Camelize }} {
    {% for metric in metrics.values() %}
    /**
     * {{ metric.description|wordwrap(wrapstring='\n     * ') }}
     */
    val {{ metric.name|Camelize }}: {{ metric.type|Camelize }}MetricType by lazy {
        {{ metric.type|Camelize }}MetricType(
            {% for arg_name, default in extra_args -%}
            {% if metric[arg_name] is defined and metric[arg_name] != default -%}
            {{ arg_name|camelize }}={{ metric[arg_name]|tojson }},
            {%- endif %}
            {%- endfor %}
        )
    };
    {% endfor %}
}
